import React from 'react'
import NavSideBar from './NavSideBar'
import MainBody from './MainBody'
import NavSideBarWritings from './NavSideBarWritings'

const Writings = () => {
  return (
    <div className="flex flex-row">
        <NavSideBarWritings/>
        <main className="border border-fuchsia-950 mx-auto justify-center align-center">
            {/* Writings */}
            <section className="writings mx-32 my-24 flex flex-col">
                {/* 1 - Given Time */}
               <article className='writing my-20 max-w-5xl' id="giventime">
                    <h3 className='writingTitle text-4xl my-12 font-semibold italic font-sans'>
                        Given Time
                    </h3>
                    <p className='writingBody first-letter:text-4xl text-justify text-base font-normal'>
                    Mi abuelo salía de paseo y algunas veces volvía con una piedra que regalaba a una de sus hijas.<br /> <br /> 
– Guarda esta piedra, mira qué bonita es.<br /> <br /> 
Ahora que él no está contemplo esas piedras y pienso en sus paseos por el campo y la mirada que escoge una piedra de entre otras miles, los criterios o la sensibilidad que apremian a que fije su atención en un objeto y lo extraiga de su hábitat. ¿Habría elegido un canto rodado en un entorno volcánico? ¿Se hubiera fijado en una malaquita semienterrada en la ladera de una montaña? Sorprende la presencia de un objeto que parece no pertenecer al lugar donde se encuentra, como si ya existiera una belleza implícita en la cadena de excepcionalidades que lo han colocado ahí. Y aunque éste parezca un criterio universal, se revela un misterio cuando descubrimos que otro elige algo en lo que tú no te hubieras fijado nunca. Es uno de los pocos momentos en los que podemos reconocer con cierto asombro que una sensibilidad distinta a la tuya ocupa otro cuerpo. Sólo podemos sentir verdadero amor si somos capaces de dejarnos fascinar por este desafío.<br /> <br /> 
Pensar en esto me ha llevado a entender que cuando mi abuelo regalaba una piedra era un gesto simpático, pero también regalaba con absoluta seriedad. Una piedra común es un objeto sin valor aparente, pero en el acto de regalar, más que una piedra se regala la mirada que encontró belleza en esa piedra como una invitación a que te unas a ese descubrimiento. La piedra no es más que el contenedor de dos miradas que buscan encontrarse en su interior.<br /> <br /> 
Los paseos de Marina por el barrio guardan similitudes con los paseos de mi abuelo y sus piedras. De camino a hacer algún recado va dirigiendo la mirada por los lugares en los que la gente deja objetos abandonados. A veces busca algo fijo, otras se deja llevar por una atención dispersa, otras pide ayuda a sus conocidos y reclama el rescate de unas características muy concretas. Cuando se queda con un objeto le busca un sitio en el estudio cuidadosamente; allí va a pasar un tiempo conviviendo con el resto de elementos consolidando una identidad, creciendo, transformándose, relacionándose.<br /> <br /> 
Los ciclos emocionales coordinan y modulan el proceso creativo hasta puntos que a veces no entendemos, sin embargo, las exposiciones de Marina tienen algo de catálogo de estados de ánimo. A Marina le gusta dejar el cuerpo abierto del proceso emocional sin huir de la aparición de momentos contradictorios o rupturas de ritmo. Así quien contempla puede reconocerse en la misma vida que resuena entre estas fisuras. Si nos adentramos en ellas podemos reconocer dos fuerzas que luchan sin fin en su trabajo: una naturaleza entrópica que devora sin piedad las frágiles estructuras de lo humano y una psicología en crisis procurando mantener orden y otorgar sentido en medio de tal absurdo. El tiempo es un vórtice terrorífico y ante el pánico que suscita, jugamos a administrarlo como un niño juega a representar un oficio adulto. Marina utiliza las agendas y los calendarios, herramientas del racionalismo, pero que también funcionan como fetiche o hechizo que nos protege de ese horror antiguo. Son como una pequeña jaula en la que encerramos los días para que no se desparramen sobre la vida convirtiéndola en caos, por eso tienen algo de compulsivo y esotérico.<br /> <br /> 
Aunque a veces pase desapercibido, los regalos tienen también que ver con la administración del tiempo. Hemos dedicado el tiempo normalmente reservado a otra cosa a decidir, construir o adquirir el regalo. Al fabricarlo como una manualidad ya no regalamos un mero objeto, sino el tiempo dedicado a éste. Quizás por eso este tipo de regalos los hacen los niños, quienes poseen poco más que su propio tiempo. El tiempo se coagula en un regalo; el regalo se carga de espíritu. Esto puede que nos haga dar cuenta de todas las energías que participan en la manifestación material del objeto, de otra manera no podríamos darle sentido. El regalo se nutre de los afectos y de las deudas, transcribe emociones que van desde el perdón hasta el deseo, fluctúa ligero por la frontera de lo manifestado y lo no manifestado. Es punto de encuentro y de intercambio, una moneda amable. Si el intercambio es entre un objeto y un “gracias”, éste no debería tener menos valor que el mismo objeto y es así que el agradecimiento puede estremecer, es consciente del desequilibrio y desea inundarlo todo.<br /> <br /> 
Vuelvo a casa y hay piedras silenciosas que se apoyan en los muebles; ya no soportan libros ni pisan papeles, no hacen otra cosa que revelar un agradecimiento que se mantiene sostenido en el tiempo.
                    </p>
               </article>
                {/*  2 - Hacer Después*/}
                <article className='writing my-20 max-w-5xl' id="hacerdespues">
                    <h3 className='writingTitle text-4xl my-12 font-semibold italic'>
                    Hacer Después
                    </h3>
                    <p className='writingBody first-letter:text-4xl text-justify text-base font-normal'>
                    Neptuno asciende, Sol desciende. Lo que era totalidad se fragmenta en mil pedazos. El otro me espeja, lo que creía que yo era se ha perdido en estos fragmentos. El otro es la referencia y la norma. Yo no soy más que algo que fue algo, algo que desaparece en un mundo de otros. Frente a estos desgarros, el afán que ensaya la reconstitución de un orden
lleva en sí la voluntad del sol   , que me recuerda que todo héroe se desarrolla en torno a lo imposible. Pero esta heroína es humilde y servicial, recoge los restos y los ensambla como puede. La oposición muestra un conflicto aparentemente antitético, y sin embargo estas fuerzas trabajan en alianza secreta: el caos se sobrepone al orden y el orden se sobrepone al caos; bajo esta perspectiva ninguno
es verdadero, pues no hay más que devenir que en su ocio eterno se presenta como fantasía estructurante.<br/><br/>
En la casa I somos transparentes, los impulsos se manifiestan sin filtrar. Júpiter y Quirón retrogradan la distancia que habían recorrido como si dudasen de esta decisión, y nos advierten de que la transparencia expande mi mundo pero también aporta dolor. La ofrezco en una intimidad espontánea, soy una lente que deja pasar la luz a través de sí y la distorsiona. Aunque quisiera desaparecer no podría dejar de distorsionar. El vidrio, sílice que fue sílice, recuerda cuando fue cosa opaca obstruyendo con su cuerpo la luminosidad; ahora modula la luz y quiere insinuar que en su transformación óptica es más liviano. Cuando pasa por la planta de reciclaje sufre múltiples transformaciones transitando por sistemas de orden y disciplina; pero las lógicas productivas de la planta, ajenas a sus reflejos y distorsiones, trituran y funden los fragmentos. Y aunque no se atiendan estas cuestiones también aquí se precisan operaciones de sensibilidad   . En un punto del proceso un láser identifica los fragmentos de cerámica para expulsarlos a otro montón y mantener el vidrio puro, que ha sido delatado por su carácter transparente. Otras máquinas separan los vidrios por criterios de tamaño y color para así acumular los trozos en montones más homogéneos. Algo parece perderse en estas transformaciones. Me resulta imposible seguir la pista de uno de esos fragmentos y reconocerlo en su coherencia al final del proceso   , las identidades provisionales no dejan fijar la mirada sobre ellas durante mucho tiempo.<br/><br/>
Antes de terminar debería saber si existe alguna identidad que no sea provisional. Ya sea sometido al fuego o al estaño (fundido o ensamblado), es en el proceso de reconstrucción donde se presenta la madurez   , pues se hace
evidente que reunir fragmentos rotos no significa volver a un estado previo. Si la identidad es una forma, cuando ésta se destruye irrumpe un intervalo confuso   bajo el cual toda estructura anterior no encuentra correspondencia con
el ahora. Éstas tensiones las sufre una persona que fue persona   , que va ensayando identidades mientras todo esto le desgarra. Cuando asumo o asimilo el devenir la forma desaparece, y así descubro que no era más que una cristalización momentánea a la que me aferré o en la que me distraje fijando la mirada. En el tiempo sin tiempo no existen las formas.
                    </p>
               </article>
                {/* 3 - Un Puente Une */}
                <article className='writing my-20 max-w-5xl' id="unpuenteune">
                    <h3 className='writingTitle text-4xl my-12 font-semibold italic'>
                        Un Puente Une
                    </h3>
                    <p className='writingBody first-letter:text-4xl text-justify text-base font-normal'>
                    Algunos filósofos unen palabras con guiones, obligando al lector a que preste atención al vínculo entre éstas. No es el mismo ser el del ser-ahí que el del ser-en-el-mundo. Yo mismo escribo deprisa estas palabras compuestas y olvido pulsar el guión de vez en cuando, la inercia me lleva a separar con un espacio y tengo que volver atrás para reconstruir la frase. Este espacio que pulso por inercia es el mismo espacio que se abre cuando pensamos a través de este lenguaje conceptual que nos sugiere observar las cosas como cerradas en sí mismas, que no nos lo pone fácil para usar el guión porque cuando lo hacemos las palabras extrañan haciendo de la lectura algo difícil y farragoso. Aquellas construcciones lingüísticas repletas de guiones tenían por objeto dinamitar un lenguaje demasiado distraído en sus espacios haciendo de los conceptos algo falsamente absoluto. Tras esta distancia insalvable un puñado de preposiciones no consigue dar cuenta de la riqueza vincular del mundo circundante. Propongo escribir un texto y colocar arbitrariamente algún recordatorio (-) para no olvidar que todo espacio es un guión-en-potencia.<br/><br/>
                    <span className='block text-center'>(-)</span>
<br/><br/>
El puente se usa para unir dos orillas que están aisladas para el libre caminar. Pero antes que puente ha de haber camino que nos conduzca a esa idea de puente, a aquel punto de mayor facilidad para el tránsito. Este doble camino es, ya en sí mismo, intención de puente. Digamos entonces que la intención preconfigura el puente. Cuando dos personas anhelan vincularse esta intención satura el espacio que aparentemente las separa hasta que emerge, inevitablemente, un puente. Un puente que ya existía pero aún no se había hecho consciente. Un puente que abre la circulación entre dos ideas de interioridad, ahora superada por otro interior más grande capaz de dar cobijo a ambas. No extraña que los puentes puedan provocar a veces temor, ya que erigir un puente es un momento delicado y tiene más de acto de fe que de cálculo; ninguna de las dos orillas conoce con seguridad de qué manera se organizará el caos cuando se abra el nuevo tránsito. Tras los puentes llegan los emisarios, las misiones, los nuevos vecinos, las cartas, el comercio, los ejércitos y las enfermedades infecciosas.<br/><br/>
<span className='block text-center'>(-)</span>
<br/><br/>
 Cuando volvemos a los guiones y a los espacios pensamos en cómo el lenguaje que nos atraviesa cotidianamente carece de puentes aparece la sospecha ¿Es posible que todo esto haya sido un error? Que toda esta construcción de mundo, esta cognición negativa que resta las cosas de aquellas que tiene a su alrededor nos haya sumido en una ilusión de aislamiento. Que vivir podría ser muy diferente si entendiésemos cada cosa en relación con todas las demás. Estos prejuicios podrían haber teñido, como es natural, la construcción científica del mundo. Mientras aún permanecemos bajo un paradigma atomista, la física moderna hace sus correcciones. La teoría de campos propone un giro total en el que los átomos y las partículas que los constituyen no son como imaginamos habitualmente y se hipotetizan como coordenadas abstractas en un campo. Nos dicen que lo que hay, si es que hay materia tal y como la entendemos, es la relación dinámica de fuerzas entre estas coordenadas, quedándonos únicamente con los vínculos. La relación sería el material ontológico fundamental; la cosa, una abstracción. Debido a la obsesión por establecer puntos fijos habríamos quedado hechizados por un mundo de ilusiones materiales, perdiendo mientras tanto la posibilidad de contemplar la exuberancia de la red de relaciones que tejen el todo. <br/><br/>
 <span className='block text-center'>(-)</span>
<br/><br/>
El puente horizontaliza: allana e iguala dos caminos para que sea posible la comunicación. Con el puente se hace necesario salvar las diferencias de nivel, pero horizontalizar no es homogeneizar, no es arrasar la diferencia sino habilitar un tránsito. Se coloca en el lugar más fácil. Nos colocamos como facilitadores en un punto de baja resistencia o, dicho de otro modo, de mayor afinidad, aquella que es imposible de fingir. De esta manera somos puente. Simpatía significa habilidad encontrando puntos de baja resistencia. Las simpatías naturales también establecen, por ley o por instinto, puentes de bajísima resistencia. De lo más pequeño a lo más grande, parece que la simpatía tiene la habilidad de configurar un orden. <br/><br/>
<span className='block text-center'>(-)</span>
<br/><br/>
Los detectives de la hermenéutica investigan la red de relaciones secretas dentro de un texto. Descubren puentes, lo que indica que esos puentes ya existían antes de que se hiciera ese trabajo. Los nexos que proponen van más allá de los que el guión establece entre una palabra y sus contiguas. La hermenéutica liga frases con frases, capítulos con palabras, versículos con espacios en blanco, los textos estudiados con los que ella misma genera. La perfección del hermeneuta es el descubrimiento de que todo estaba relacionado con todo, que el texto investigado era una única palabra compuesta, que en su colosal polisemia puede ser descompuesta y articulada en frases y otras subdivisiones. Son una serie de vicios lingüísticos los que nos impiden entender esta otra realidad al instante y comenzar así a leer como cualquier forma de vida lee al resto de la naturaleza de la cual no se siente separada. De este lenguaje torpe e insuficiente emergen símbolos (-) que no pueden hacer gran cosa, salvo quizás abrir pequeñas grietas a una realidad oceánica de una magnitud que aún causa angustia si se muestra sin estas necesarias domesticaciones cognitivas. <br/><br/>

<span className='block text-center'>(-)</span> <br/><br/>
Nuestro primer puente: aquel que salva la distancia entre adentro y afuera. Puente previo a toda acción, palabra o pensamiento. La escisión entre sujeto y objeto representa la heroicidad del momento moderno en el que un ser humano muy asustado ha creído dominar las cosas definitivamente. Para lograr esto ha tenido que desposeerlas de su espíritu y convertirlas en máquinas, un precio altísimo. Esta manera de reconocer la correspondencia entre adentro y afuera es otro vicio más de un lenguaje insuficiente, y la tendencia que provoca es infravalorar lo subjetivo en pos de una objetividad que nunca fue la cosa prometida. El afuera no será jamás esa realidad aislada, inanimada y mecánica porque aún quedan innumerables puentes por descubrir. De acuerdo con este problema la arquitecta que construye puentes puede dejarse seducir por la fría objetividad que impone una idea inerte sobre un entorno animado o, por el contrario, puede intuir la red relacional que se inaugura con el puente y cómo impacta esta en la ya existente. Creemos que puede aproximarse con una construcción que no domina ni posee, sino que cohabita y simpatiza con el lugar. Lograr esta afinidad dependerá de la sensibilidad con la que transite su dentro-fuera en sucesivos pasos que le llevarán de una idea a un boceto, de un boceto a una maqueta y de una maqueta a una construcción. Decíamos: la intención preconfigura el puente; el camino nos lleva al puente. Un buen camino nos llevará, seguro, a un buen puente.
                    </p>
               </article>
                {/*  4 - Formas de Empezar un Cuento*/}
               <article className='writing my-20 max-w-5xl' id="formasdeempezaruncuento">
                    <h3 className='writingTitle text-4xl my-12 font-semibold italic font-sans'>
                        Formas de Empezar un Cuento
                    </h3>
                    <p className='writingBody first-letter:text-4xl text-justify text-base font-normal'>
                    El manto indica el umbral tras el cual no hay más que contingencia y se desplaza sinuoso, a veces avanzando, otras retrocediendo. Cuando éste le gana terreno al mundo de lo manifestado todo es más ligero, un poco más imposible de lo imposible que es siempre todo. <br /><br />
La inspiración, la confusión y la melancolía son manifestaciones de Neptuno, que empaña la vida para devolvernos al sueño que siempre fue. La brusquedad de la vigilia obliga a los objetos a ser algo duro y diferenciado; tenemos que orientarnos, aunque sea provisionalmente.<br /><br />
La vigilia obliga a sostener, el sueño obliga al cambio y la transformación.<br /><br />
Desde este lado no quedan cosas por imaginar. Hemos de esperar a que la niebla avance y lo vuelva a engullir todo para que reaparezca renovado, transformado y libre. Se nos ha restringido la visión a unos pocos metros a nuestro alrededor y ahora el mundo emerge a partir de nuestro movimiento. La espesura es efervescente. Si miras sin poner la atención en nada concreto la percibirás acercándose; se acerca tanto que amenaza la posibilidad de disolución, de perderte tú también junto al resto de cosas que quedan detrás. Sin embargo, nada ocurre; te disuelves suave, imperceptible. La transición es tan agradable que caes en la cuenta que lo realmente angustioso es mantener la coherencia de ser algo. Un cuerpo que anhela ligereza no quiere mantenerse anclado.
                    </p>
               </article>
                {/* 5 Corazon y Ornamento */}
                <article className='writing my-20 max-w-5xl ' id="corazayornamento">
                    <h3 className='writingTitle text-4xl my-12 font-semibold italic font-sans'>
                        Coraza y Ornamento
                    </h3>
                    <p className='writingBody first-letter:text-4xl text-justify text-base font-normal'>
                    Levanto la carta para el 6/4/2023 a las 18:50 en Sagunto. <br /> <br />
(Plutón en Acuario la cúspide de V) el dramático nos invita a develar secretos, pero esta vez con un ánimo lúdico. Exploramos las entrañas de un objeto y la crudeza de su exposición interna es la ingeniería que sustenta su coraza (Venus trígono Plutón) que se mimetiza con un ornamento. Quizá porque también observamos la piel y el pelo de nuestros cuerpos como ornamento nos horroriza si se manifiesta inesperadamente la imagen de un interior que antes funcionaba silencioso y oculto. Preferimos lidiar con la carcasa, y otorgamos -creyendo que alguien lo hizo por nosotros- a la cara visible de las cosas el acceso principal, a partir del cual se articulan una serie de lógicas afines a mostrarse y aparecer (Venus sextil Neptuno en VII). <br /> <br />
En oposición a esto (Sol oposición Luna), sentimos que algo se escapa cuando accedemos a ellas a través del aspecto bajo el que parecen indicarnos cómo han de ser vistas. Prevalece la suspicacia ante la ilusión que nos distrae de lo realmente decisivo. En este sentido, no consideramos que poseamos una auténtica sensación de dominio sobre la cosa hasta que no descubrimos algún secreto, algo que nos permita comprender las relaciones ocultas que ligan lo más visible con lo menos visible, lo aparente y lo oculto, la superestructura y la infraestructura.<br /> <br /> 
La Luna gira en sincronización exacta con su desplazamiento para mantener constantemente una cara oculta desde su visión terrestre. Aún no hemos caído lo suficiente en lo extraño de este movimiento. La ocultación es relativa: el patio de butacas en la Tierra frente al escenario en la cara visible de la Luna, que cuenta con las bambalinas adecuadas (Neptuno en VII) para que la ficción sea posible. Puede que haya que indagar más en esa cara oculta, pues no es prudente que cosas tan importantes como las largas noches de poesía insomne, la cólera del licántropo, la agitación de las mareas o la maduración del ciclo menstrual estén afectadas por un movimiento tan sospechoso. Dejémonos invadir por la paranoia tirando de la cortina y quizá podremos descubrir a los actores fumando entre bambalinas junto a los decorados de cartón-piedra. Todavía no sabemos si esto será liberador o nos quedará la sensación de haberlo jodido todo.<br /> <br /> 
(Saturno en Piscis en la cúspide de la VI) viene de trabajar a lo largo de toda la rueda; cuando llega a (Piscis) se detiene ante un océano sin forma y muere ahogado. La marquetera abandona la disciplina de una tradición agonizante y los secretos de oficio se revelan con la luz filtrada entre las grietas. Las formas ya no se corresponden con los motivos que antes reconocíamos: en su cambio de escala se han desnaturalizado, son superficies de material frágil sin función aparente.
                    </p>
               </article>
             
               



            </section>
        </main>
    </div>
  )
}

export default Writings